update docker

diff --git a/.github/workflows/next-to-cloud-run.yml b/.github/workflows/next-to-cloud-run.yml
--- a/.github/workflows/next-to-cloud-run.yml
+++ b/.github/workflows/next-to-cloud-run.yml
@@ -43,9 +43,16 @@ jobs:
         with:
           version: ">= 363.0.0"
 
+      - name: "Check Dockerfile presence"
+        run: |
+          if [ ! -f ./Dockerfile ]; then
+            echo "Dockerfile not found in the root directory."
+            exit 1
+          fi
+
       - name: "Build and push Docker image"
         run: |
-          gcloud auth configure-docker
+          gcloud auth configure-docker --quiet
           docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/finance .
           docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/finance
 
